"""Generate the small public-repository baseline from one canonical source."""

import argparse
import json
from pathlib import Path
import sys


HERE = Path(__file__).resolve().parent
PROFILES = json.loads((HERE / "repository-profiles.json").read_text(encoding="utf-8"))
ROLES = {
    "core": "pennilogic-core-reviewer", "qa": "pennilogic-qa",
    "security": "pennilogic-security-reviewer", "privacy": "pennilogic-privacy-reviewer",
    "money": "pennilogic-money-reviewer", "contract": "pennilogic-contract-reviewer",
    "compliance": "pennilogic-compliance-reviewer",
    "accessibility": "pennilogic-accessibility-reviewer", "design": "pennilogic-design-reviewer",
    "reliability": "pennilogic-reliability-reviewer", "release": "pennilogic-release-reviewer",
}
HEADER = "<!-- Generated by PenniLogic/infra governance/generate.py; edit the canonical source. -->\n"
SAFETY = """- Never commit credentials, production data, raw SMS/email or user financial records.
- Keep money in integer minor units plus currency; calculations are deterministic and server-authoritative.
- Keep ledger history append-only, sharing default-deny and entitlements enforced by the server.
- The app must remain usable when optional permissions are denied.
- Preserve other agents' files, branches and findings; one active writer per checkout.
- Use additive contracts and serialize database migrations and protected merges.
- No paid runner, provider, storage allowance increase or production deployment without explicit approval.
"""


def encoded(value):
    return json.dumps(value, indent=2) + "\n"


def tool_steps(profile):
    actions = PROFILES["actions"]
    steps = [
        {"name": "Checkout", "uses": f"actions/checkout@{actions['checkout']}",
         "with": {"persist-credentials": False, "fetch-depth": 0}},
        {"name": "Python", "uses": f"actions/setup-python@{actions['setup-python']}",
         "with": {"python-version": PROFILES["python"]}},
    ]
    if "java" in profile:
        steps.append({
            "name": "JDK", "uses": f"actions/setup-java@{actions['setup-java']}",
            "with": {"distribution": "microsoft", "java-version": profile["java"]},
        })
    return steps


def workflow(repo, setup=False):
    profile = PROFILES["repositories"][repo]
    steps = tool_steps(profile)
    commands = ["python scripts/check_repository.py"] if setup else profile["commands"]
    steps.append({"name": "Verify repository" if setup else "Run checks", "run": "\n".join(commands)})
    if repo == "api" and not setup:
        steps.append({
            "name": "Coverage against explicit base",
            "env": {"BASE_SHA": "${{ github.event.pull_request.base.sha || github.sha }}"},
            "run": 'python scripts/quality.py coverage --base "$BASE_SHA"',
        })
    if setup:
        steps.append({"name": "Install managed hook", "run": "python scripts/setup.py"})
    events = {"workflow_dispatch": {}}
    if not setup:
        events.update({"push": {"branches": ["main"]}, "pull_request": {"branches": ["main"]}})
    return encoded({
        "name": "Copilot Setup Steps" if setup else "CI",
        "on": events,
        "permissions": {"contents": "read"},
        "concurrency": {
            "group": "${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}",
            "cancel-in-progress": True,
        },
        "jobs": {
            "copilot-setup-steps" if setup else "ci": {
                "name": "Copilot setup" if setup else "CI",
                "runs-on": PROFILES["runner"],
                "timeout-minutes": 30 if repo == "api" else 10,
                "steps": steps,
            }
        },
    })


def artifacts(repo):
    profile = PROFILES["repositories"][repo]
    commands = "\n".join(profile["commands"])
    policy = {
        "version": 1, "repository": f"PenniLogic/{repo}", "repository_id": profile["id"],
        "required_native_check": "CI", "review_roles": ROLES,
        "commands": profile["commands"],
        "review_floor": ["core"], "behavior_changes_add": ["qa"],
        "review_identity": "Separate non-author AI sessions; one GitHub user, not two-human approval.",
        "github_approving_review_count": 0, "mandatory_commit_signatures": False,
        "no_bypass": True,
    }
    return {
        ".gitignore": """.env
.env.*
!.env.example
!.env.sample
.venv/
__pycache__/
*.pyc
.gradle/
build/
node_modules/
.next/
coverage/
.idea/
.DS_Store
""",
        "AGENTS.md": HEADER + f"""# PenniLogic/{repo}

{profile['purpose']}.

**Current scope:** {profile['state']}

Read this file, the linked plan item, relevant product decisions and
`.github/agent-policy.json`. This new public repository has its own delivery
baseline; private-era setup holds remain recorded in PenniLogic-old, not copied
as assertions that unfinished product work is accepted here.

## Delivery

Use an issue-sized branch and a pull request. Continue an existing task rather
than opening a duplicate. After the initial reviewed import, do not push to
protected main, bypass a failing check, or rewrite reviewed history.
Perform two self-reviews: correctness/diff hygiene, then security/privacy/money
and edge cases. Get a separate non-author Core review; behavior changes also
need QA, and actual affected risks need the matching specialist. A required
negative review blocks integration. Record reviewer session, reviewed commit,
findings and evidence in the PR; one GitHub account cannot provide two-human
approval. No custom CheckRun publisher or self-reported identity is proof of
independence.

GitHub requires the real native `CI` job, PR-only integration, resolved threads
and current base. Its approving-review count is zero because the sole account
cannot approve its own PR. Never invent another GitHub reviewer.

## Commands

```text
python scripts/setup.py
{commands}
```

Install the managed hook with the documented setup command. Preserve a custom
hook rather than replacing it. Never claim an unrun build, test, accessibility
or load gate passed; foundation checks are not product acceptance.

## Safety

{SAFETY}
## Shared setup

`PenniLogic/infra/governance` owns generated setup. Edit that source and regenerate;
do not maintain divergent generated files. Shared agent profiles live in
`PenniLogic/.github/agents`. `.github/github-app.yml` provides manual scripts;
its presence does not imply app trust or automatic execution.
""",
        ".github/copilot-instructions.md": HEADER + """# Copilot entry point

Read `AGENTS.md`, `.github/agent-policy.json`, the task and relevant product decisions
before work. Use the repository's actual commands. Keep one writer per checkout;
implementers never review their own change as an independent agent. Return real
results and explicit failures. Do not enable paid services or automatic remote control.
""",
        "CONSTITUTION.md": HEADER + """# Public project charter

Deliver useful product increments, not more process. Preserve the old private
organization and its history; do not declare its unresolved findings cleared by
this migration. The public operating policy is in
`PenniLogic/docs/governance/DELIVERY.md`.

Use one writer per checkout, real tests, separate non-author review, current-base
PR-only merges and empty bypass. One GitHub owner with multiple AI sessions is
procedural separation, not two-person approval. Do not override negative findings.

""" + SAFETY,
        "COPILOT_FILES.md": HEADER + """# Copilot setup

- `AGENTS.md`: repository scope, commands, review and safety rules.
- `.github/copilot-instructions.md`: repository Copilot entry point.
- `.github/instructions/source.instructions.md`: source-specific safety guidance.
- `.github/agent-policy.json`: small public-repository review-role declaration.
- `PenniLogic/.github/agents`: shared Developer, Producer, QA and specialist profiles.
- `.github/github-app.yml`: manual commands only; the app must review/trust it.
- `.github/workflows/copilot-setup-steps.yml`: standard hosted cloud-agent setup.

`CONSTITUTION.md` is explicitly referenced documentation, not an automatically
discovered filename. Cloud setup config does not grant a Copilot subscription,
prove that an agent ran, or authorize spending. No automatic remote control,
credential hook, self-hosted runner or custom status publisher is configured.
""",
        ".github/instructions/source.instructions.md": """---
applyTo: "**/*.kt,**/*.py,**/*.ts,**/*.tsx,**/*.java,**/*.tf"
---

Read AGENTS.md and the relevant contract before editing. Test actual behavior and
negative cases. Keep secrets and raw user messages out of source, fixtures and logs.
Money is deterministic integer minor units with currency; authorization and sharing
are default-deny. Use a separate non-author review and keep runtime boundaries intact.
""",
        ".github/agent-policy.json": encoded(policy),
        ".github/workflows/ci.yml": workflow(repo),
        ".github/workflows/copilot-setup-steps.yml": workflow(repo, setup=True),
        ".github/github-app.yml": encoded({
            "instructions": "Read AGENTS.md and the current task; keep one writer per checkout.",
            "scripts": [
                {"name": "Install managed hook", "command": "python scripts/setup.py"},
                {"name": "Repository checks", "command": "python scripts/check_repository.py"},
            ],
            "automation": {"auto_issue_session": False, "remote_control": False},
        }),
        ".github/CODEOWNERS": f"* @{PROFILES['owner']}\n",
        ".github/ISSUE_TEMPLATE/task.yml": encoded({
            "name": "Delivery task", "description": "A bounded product or setup change",
            "body": [
                {"type": "textarea", "id": "outcome", "attributes": {
                    "label": "Outcome", "description": "What observable behavior or artifact should change?"
                }, "validations": {"required": True}},
                {"type": "textarea", "id": "acceptance", "attributes": {
                    "label": "Acceptance and verification",
                    "description": "List real checks, affected risks and explicit exclusions."
                }, "validations": {"required": True}},
                {"type": "textarea", "id": "dependencies", "attributes": {
                    "label": "Dependencies and source backlog item",
                    "description": "Link the existing card, contracts and blocking decisions. Do not paste credentials or user data."
                }}
            ]
        }),
        ".github/ISSUE_TEMPLATE/config.yml": encoded({
            "blank_issues_enabled": False,
            "contact_links": [{
                "name": "Private security reports",
                "url": f"https://github.com/PenniLogic/{repo}/security/advisories/new",
                "about": "Do not disclose vulnerabilities or sensitive data in a public issue.",
            }],
        }),
        ".github/pull_request_template.md": """## Outcome

Describe the implemented result and link the existing plan item.

## Validation

List exact commands, actual results and omitted checks with reasons.

## Self-review

Record correctness/diff review and adversarial security/privacy/money review.

## Independent review

Record the separate non-author reviewer session, exact reviewed commit, role,
findings and evidence. This is procedural AI separation, not two-human approval.
Do not merge while required findings remain unresolved.

## Risks, rollout and rollback

Describe the changed behavior, safety boundaries and reversal.
""",
        "CONTRIBUTING.md": HEADER + f"""# Contributing

Read [AGENTS.md](AGENTS.md). {profile['state']}

Install Python 3.14, Git{', and JDK 21' if repo == 'api' else ''}, then run:

```text
python scripts/setup.py
{commands}
```

`CI` runs on standard GitHub-hosted Ubuntu for pushes and pull requests, including
forks, with read-only permissions and no repository secrets. Actions are SHA-pinned.
Workflow/config files generated here use JSON syntax, a valid YAML subset, so
the stdlib checker can validate them without installing a second parser.

Branches and small PRs remain required after the initial import. Record two
self-reviews and separate agent review. Do not request self-approval from the
only GitHub user. Apply specialist review to the changed risks. Preserve failures;
do not manufacture reports, check results or reviewer identities.

Generated setup is maintained in `PenniLogic/infra/governance`. Development builds
and tests belong in this repository as its implementation is added.
""",
        "SECURITY.md": HEADER + """# Security

Use GitHub **Security > Report a vulnerability** for private reports when enabled.
Otherwise contact the repository owner privately; do not post exploit details,
credentials or production data in a public issue.

Public CI never receives application/provider secrets and uses disposable standard
GitHub-hosted runners. It does not use the old private shared server. Free public
secret scanning and push protection are configured separately; verify the live
settings rather than treating this document as evidence.

""" + SAFETY,
        "README.md": HEADER + f"""# PenniLogic {repo.lstrip('.')}

{profile['purpose']}.

**Status:** {profile['state']}

This repository belongs to the new public, Free-plan `PenniLogic` organization.
`migration-source.json` records the pinned source snapshot and excluded history.
The old private repositories, unmerged branches and discussions remain in
`PenniLogic-old`; setup migration does not mark their product tasks Done.

## Develop

```text
python scripts/setup.py
{commands}
```

See [AGENTS.md](AGENTS.md) and [CONTRIBUTING.md](CONTRIBUTING.md).
Product specifications and the preserved backlog are in
[PenniLogic/docs](https://github.com/PenniLogic/docs).

## Cost and permissions

Only standard GitHub-hosted runners are configured. Public-repository runner
minutes are free; paid larger runners, storage overages, Copilot usage, external
APIs and deployments are not automatically free and are not authorized here.
No release publishing, artifact upload or cache allowance increase is configured.
There is one GitHub owner with multiple independent AI sessions, not multiple humans.

No open-source license was selected by this setup migration; public visibility
alone is not a license grant. Existing source notices are preserved.
""",
        ".gitattributes": "* text=auto eol=lf\n*.jar binary\n",
        "scripts/check_repository.py": (HERE / "templates/check_repository.py").read_text(encoding="utf-8"),
        "scripts/setup.py": (HERE / "templates/setup.py").read_text(encoding="utf-8"),
    }


def generate(repo, root, check=False):
    mismatches = []
    for name, content in artifacts(repo).items():
        path = root / name
        if path.is_symlink():
            raise ValueError(f"Refusing generated symlink: {name}")
        expected = content.encode("utf-8")
        if check:
            if not path.is_file() or path.read_bytes() != expected:
                mismatches.append(name)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(expected)
    if mismatches:
        raise ValueError("Generated setup differs: " + ", ".join(mismatches))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repository", choices=PROFILES["repositories"])
    parser.add_argument("--root", type=Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    try:
        if args.repository:
            generate(args.repository, args.root or Path.cwd(), args.check)
        else:
            if args.root is None:
                parser.error("--root is required for all-repository generation")
            for repo in PROFILES["repositories"]:
                generate(repo, args.root / repo, args.check)
        print("Public repository baseline " + ("verified." if args.check else "generated."))
        return 0
    except (OSError, ValueError) as error:
        print(str(error), file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
